Feature: Lyrics synchronization and absolute paths
sagemtl/SageKaraoke pull request #2
Opened 2020-12-29 23:21 UTC by yutongliuytl

Lyrics synch:
- Added parser for LRC formatting data, and lyrics display timing logic
- Added placeholder test data until the backend endpoint is complete

Absolute paths:
- jsconfig.json file added to support absolute paths from 'src' folder (access pages with `pages/`)

2020-12-30 17:14 UTC, jiaweisun-github approved these changes

2020-12-30 17:17 UTC, cxy2015ca requested changes
Can you restructure the folders?
Export the lyrics part as a global component instead of creating a song page for it, because we'll be using them in the preview page and ktv page.
Sorry for the nit, might as well give it better structure from the start :D

2020-12-30 19:40 UTC, yutongliuytl commented
Right that is a good point, I will try to abstract lyrics/audio into the global component:)
Originally, I implemented the lyrics in the video/ktv page but I named it "Song" and the url into `song/name-of-song`, maybe there is a better naming convention for it

2021-01-01 22:19 UTC, cxy2015ca approved these changes

2021-01-01 23:43 UTC, merged