test, don't merge
sagemtl/SageKaraoke pull request #5
Opened 2021-01-06 20:44 UTC by cxy2015ca

2021-01-08 21:59 UTC, yutongliuytl commented on src/pages/Preview/containers/Preview.js
> +  const [karaokeState, karaokeDispatch] = globalContext.karaoke;
The following changes made the dependencies array error go away, adding after this line: `const { playSong } = karaokeState;`

2021-01-08 21:59 UTC, yutongliuytl commented on src/pages/Preview/containers/Preview.js
> +  };
Changing this to: ` const setPlaySong = useCallback((play) => {
      karaokeDispatch({
        type: 'SET_PLAYSONG',
        payload: { playSong: play },
      });
    },
    [karaokeDispatch],
  );`

2021-01-08 22:00 UTC, yutongliuytl commented on src/pages/Preview/containers/Preview.js
> +  }, []);
having these dependencies set to: `[karaokeDispatch, setPlaySong, playSong]`

2021-01-08 22:03 UTC, yutongliuytl requested changes
Tested and the audio works well damn 😎 

I did have warnings though and the quick comment changes that I added on the files worked for me, let me know if it doesn't workkk

2021-01-08 22:05 UTC, jiaweisun-github approved these changes

2021-01-10 02:07 UTC, cxy2015ca commented
@yutongliuytl changed

2021-01-10 22:21 UTC, xinruili07 approved these changes

2021-01-10 22:48 UTC, yutongliuytl approved these changes
👍

2021-01-10 22:49 UTC, merged